// AUTO-GENERATED by scripts/quality/build-age-access-policy.mjs
// Source of truth: config/age-access-policy.json
// Do not edit manually.

export const AGE_ACCESS_POLICY_VERSION = 1 as const;
export const AGE_ACCESS_MODE = 'DECLARATION_FIRST' as const;
export const AGE_ACCESS_ALLOWS_SELF_DECLARATION = true as const;
