// AUTO-GENERATED by scripts/quality/build-media-format-policy.mjs
// Source of truth: config/media-formats.json
// Do not edit manually.

export const MEDIA_FORMAT_POLICY_VERSION = 3 as const;

export const IMAGE_INPUT_FORMATS = [
  {
    "extension": "jpg",
    "mimeTypes": [
      "image/jpeg",
      "image/jpg"
    ],
    "browserPreviewLikely": true,
    "editable": true,
    "preservesTransparency": false
  },
  {
    "extension": "jpeg",
    "mimeTypes": [
      "image/jpeg"
    ],
    "browserPreviewLikely": true,
    "editable": true,
    "preservesTransparency": false
  },
  {
    "extension": "png",
    "mimeTypes": [
      "image/png"
    ],
    "browserPreviewLikely": true,
    "editable": true,
    "preservesTransparency": true
  },
  {
    "extension": "webp",
    "mimeTypes": [
      "image/webp"
    ],
    "browserPreviewLikely": true,
    "editable": true,
    "preservesTransparency": true
  }
] as const;
export const IMAGE_INPUT_MIME_TYPES = [
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/webp"
] as const;
export const IMAGE_INPUT_EXTENSIONS = [
  "jpg",
  "jpeg",
  "png",
  "webp"
] as const;
export const IMAGE_OUTPUT_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp"
] as const;
export const IMAGE_MAX_BYTES = 10485760 as const;
export const AVATAR_IMAGE_MAX_BYTES = 8388608 as const;
export const VIDEO_POSTER_IMAGE_MAX_BYTES = 10485760 as const;
export const IMAGE_EDITOR_PRESETS = {
  "free": {
    "aspectRatio": "original",
    "lockAspectRatio": false,
    "maxOutputEdge": 2048,
    "lossyQuality": 0.88
  },
  "profile-photo": {
    "aspectRatio": "original",
    "lockAspectRatio": false,
    "maxOutputEdge": 2048,
    "lossyQuality": 0.88
  },
  "avatar-square": {
    "aspectRatio": "square",
    "lockAspectRatio": true,
    "maxOutputEdge": 1024,
    "lossyQuality": 0.9
  },
  "community-cover": {
    "aspectRatio": "landscape",
    "lockAspectRatio": true,
    "maxOutputEdge": 2048,
    "lossyQuality": 0.88
  },
  "social-feed": {
    "aspectRatio": "original",
    "lockAspectRatio": false,
    "maxOutputEdge": 2048,
    "lossyQuality": 0.88
  }
} as const;
export const IMAGE_FORMAT_LABEL = "JPG, JPEG, PNG ou WebP" as const;
export const IMAGE_INPUT_ACCEPT = [...IMAGE_INPUT_MIME_TYPES, ...IMAGE_INPUT_EXTENSIONS.map((extension) => `.${extension}`)].join(',');

export const VIDEO_INPUT_FORMATS = [
  {
    "extension": "mp4",
    "mimeTypes": [
      "video/mp4"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": true
  },
  {
    "extension": "m4v",
    "mimeTypes": [
      "video/x-m4v"
    ],
    "canonicalMimeType": "video/mp4",
    "browserPreviewLikely": true
  },
  {
    "extension": "mov",
    "mimeTypes": [
      "video/quicktime"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": false
  },
  {
    "extension": "webm",
    "mimeTypes": [
      "video/webm"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": true
  },
  {
    "extension": "mkv",
    "mimeTypes": [
      "video/x-matroska"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": false
  },
  {
    "extension": "avi",
    "mimeTypes": [
      "video/x-msvideo",
      "video/avi",
      "video/msvideo"
    ],
    "canonicalMimeType": "video/x-msvideo",
    "browserPreviewLikely": false
  },
  {
    "extension": "wmv",
    "mimeTypes": [
      "video/x-ms-wmv"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": false
  },
  {
    "extension": "ts",
    "mimeTypes": [
      "video/mp2t"
    ],
    "canonicalMimeType": null,
    "browserPreviewLikely": false
  },
  {
    "extension": "mts",
    "mimeTypes": [
      "video/mp2t"
    ],
    "canonicalMimeType": "video/mp2t",
    "browserPreviewLikely": false
  },
  {
    "extension": "m2ts",
    "mimeTypes": [
      "video/mp2t"
    ],
    "canonicalMimeType": "video/mp2t",
    "browserPreviewLikely": false
  },
  {
    "extension": "mxf",
    "mimeTypes": [
      "application/mxf",
      "video/mxf"
    ],
    "canonicalMimeType": "application/mxf",
    "browserPreviewLikely": false
  }
] as const;
export const VIDEO_INPUT_MIME_TYPES = [
  "video/mp4",
  "video/x-m4v",
  "video/quicktime",
  "video/webm",
  "video/x-matroska",
  "video/x-msvideo",
  "video/avi",
  "video/msvideo",
  "video/x-ms-wmv",
  "video/mp2t",
  "application/mxf",
  "video/mxf"
] as const;
export const VIDEO_INPUT_EXTENSIONS = [
  "mp4",
  "m4v",
  "mov",
  "webm",
  "mkv",
  "avi",
  "wmv",
  "ts",
  "mts",
  "m2ts",
  "mxf"
] as const;
export const VIDEO_PUBLIC_PLAYBACK_MIME_TYPES = [
  "video/mp4",
  "video/webm"
] as const;
export const VIDEO_MAX_BYTES = 524288000 as const;
export const VIDEO_FORMAT_LABEL = "MP4, M4V, MOV, WebM, MKV, AVI, WMV, TS, MTS, M2TS ou MXF" as const;
export const VIDEO_INPUT_ACCEPT = [...VIDEO_INPUT_MIME_TYPES, ...VIDEO_INPUT_EXTENSIONS.map((extension) => `.${extension}`)].join(',');

export const CANONICAL_VIDEO_OUTPUT = {
  "container": "mp4",
  "videoCodec": "h264",
  "audioCodec": "aac"
} as const;
