// AUTO-GENERATED by scripts/quality/build-community-contracts.mjs
// Source of truth: config/community-contracts.json
// Do not edit manually.

export const COMMUNITY_CONTRACT_VERSION = 1 as const;

export const COMMUNITY_SOURCE_TYPES = [
  "community",
  "venue"
] as const;
export type CommunitySourceType = typeof COMMUNITY_SOURCE_TYPES[number];

export const COMMUNITY_JOIN_POLICIES = [
  "open",
  "approval",
  "invite_only"
] as const;
export type CommunityJoinPolicy = typeof COMMUNITY_JOIN_POLICIES[number];

export const COMMUNITY_VIEWER_ROLES = [
  "owner",
  "admin",
  "moderator",
  "member"
] as const;
export type CommunityViewerRole = typeof COMMUNITY_VIEWER_ROLES[number];

export const COMMUNITY_VIEWER_MODES = [
  "visitor",
  "pending",
  "member",
  "moderator",
  "manager"
] as const;
export type CommunityViewerMode = typeof COMMUNITY_VIEWER_MODES[number];

export const COMMUNITY_LIFECYCLE_STATUSES = [
  "active",
  "paused",
  "dormant",
  "archived",
  "scheduled_for_deletion"
] as const;
export type CommunityLifecycleStatus = typeof COMMUNITY_LIFECYCLE_STATUSES[number];

function includesString<T extends readonly string[]>(values: T, value: unknown): value is T[number] {
  return typeof value === 'string' && (values as readonly string[]).includes(value);
}

export function isCommunitySourceType(value: unknown): value is CommunitySourceType {
  return includesString(COMMUNITY_SOURCE_TYPES, value);
}

export function isCommunityJoinPolicy(value: unknown): value is CommunityJoinPolicy {
  return includesString(COMMUNITY_JOIN_POLICIES, value);
}

export function isCommunityViewerRole(value: unknown): value is CommunityViewerRole {
  return includesString(COMMUNITY_VIEWER_ROLES, value);
}

export function isCommunityViewerMode(value: unknown): value is CommunityViewerMode {
  return includesString(COMMUNITY_VIEWER_MODES, value);
}

export function isCommunityLifecycleStatus(value: unknown): value is CommunityLifecycleStatus {
  return includesString(COMMUNITY_LIFECYCLE_STATUSES, value);
}
